"""
pipeline/file_tracker.py
────────────────────────
Idempotency layer for the FastFeast pipeline.

Uses file_path + file_hash together as the idempotency key.

Same file path + same hash  → already processed → SKIP
Same file path + new hash   → file regenerated  → PROCESS
New file path               → new file          → PROCESS

The hash is computed from the file content using SHA-256
before any parsing begins. This means even if a file is
rewritten with the same name, it will be reprocessed only
if the content actually changed.
"""

from __future__ import annotations

import hashlib
import os

from pipeline.utils.db import get_cursor, get_dict_cursor
from pipeline.utils.retry import db_retry
from pipeline.logging.logger import get_logger_name

logger = get_logger_name(__name__)


def compute_file_hash(file_path: str, chunk_size: int = 65536) -> str:
    """
    Compute SHA-256 hash of a file.
    
    Args:
        file_path: Path to the file.
        chunk_size: Bytes to read per chunk (default 64KB).
    
    Returns:
        Hexadecimal SHA-256 hash string (64 characters).
    
    Raises:
        OSError: If file cannot be read.
    """
    sha256 = hashlib.sha256()
    with open(file_path, 'rb') as f:
        for chunk in iter(lambda: f.read(chunk_size), b''):
            sha256.update(chunk)
    return sha256.hexdigest()


def get_file_size_bytes(file_path: str) -> int:
    """Get file size in bytes."""
    return os.path.getsize(file_path)


def is_file_processed(file_path: str, file_hash: str) -> bool:
    """
    Return True if this exact file (same path AND same hash) was already
    successfully processed.
    """
    # If file doesn't exist, it can't be processed 
    if not os.path.exists(file_path):
        return False
    
    with get_dict_cursor() as cur:
        cur.execute(
            """
            select 1 from warehouse.file_tracker
            where file_path = %s
              and file_hash  = %s
              and status     = 'success'
            limit 1
            """,
            (file_path, file_hash)
        )
        row = cur.fetchone()
        already_done = row is not None

        if already_done:
            logger.debug(
                "file_already_processed",
                file=file_path,
                hash=file_hash[:8]
            )
        else:
            logger.debug(
                "file_not_processed_yet",
                file=file_path,
                hash=file_hash[:8]
            )

        return already_done


@db_retry
def register_file(
    run_id: int,
    file_path: str,
    file_hash: str,
    file_type: str,
) -> None:
    """
    Register a file as 'processing' in file_tracker.
    Uses ON CONFLICT on the composite key (file_path, file_hash)
    to reset the row cleanly on retry.

    Args:
        run_id:          Generated by audit_trail.start_run().
        file_path:       Full path to the file.
        file_hash:       SHA-256 of file content.
        file_type:       'batch' or 'stream'.
    """
    with get_cursor() as cur:
        cur.execute(
            """
            insert into warehouse.file_tracker
                (file_path, file_hash, file_type, status, processed_at, pipeline_run_id)
            values (%s, %s, %s, 'processing', now(), %s)
            on conflict (file_path, file_hash) do update
                set
                    status          = 'processing',
                    processed_at    = now(),
                    pipeline_run_id = excluded.pipeline_run_id
            """,
            (file_path, file_hash, file_type, run_id)
        )

    logger.debug(
        "file_registered",
        run_id=run_id,
        file=file_path,
        hash=file_hash[:8],
        type=file_type
    )


@db_retry
def mark_file_success(
    file_path: str,
    file_hash: str,
    records_total: int,
    records_loaded: int,
    records_quarantined: int,
) -> None:
    """
    Mark a file as successfully processed.
    Call only after warehouse upsert committed.

    Args:
        file_path:          Source file path.
        file_hash:          Hash of the file (must match).
        records_total:      Total records read from the file.
        records_loaded:     Records successfully loaded to the warehouse.
        records_quarantined: Records sent to quarantine.
    """
    with get_cursor() as cur:
        cur.execute(
            """
            update warehouse.file_tracker
            set
                status              = 'success',
                records_total       = %s,
                records_loaded      = %s,
                records_quarantined = %s,
                processed_at        = now()
            where file_path = %s
              and file_hash  = %s
            """,
            (records_total, records_loaded, records_quarantined, file_path, file_hash)
        )

    logger.info(
        "file_success",
        file=file_path,
        hash=file_hash[:8],
        records_total=records_total,
        records_loaded=records_loaded,
        records_quarantined=records_quarantined
    )


@db_retry
def mark_file_failed(file_path: str, file_hash: str, error_message: str) -> None:
    """
    Mark a file as failed.
    Call after any unrecoverable processing error.

    Args:
        file_path:      Source file path.
        file_hash:      Hash of the file (must match).
        error_message:  Error description.
    """
    with get_cursor() as cur:
        cur.execute(
            """
            update warehouse.file_tracker
            set
                status      = 'failed',
                processed_at = now()
            where file_path = %s
              and file_hash  = %s
            """,
            (file_path, file_hash)
        )

    logger.warning(
        "file_failed",
        file=file_path,
        hash=file_hash[:8],
        error=error_message
    )